version: 2

sources:
  - name: ynab
    schema: source
    description: table replicas of ynab budget json responses
    tables:
      - name: ynab_accounts
        meta:
          dagster:
            asset_key: ["ynab_accounts"]
      - name: ynab_categories
        meta:
          dagster:
            asset_key: ["ynab_categories"]
      - name: ynab_payees
        meta:
          dagster:
            asset_key: ["ynab_payees"]
      - name: ynab_transactions
        meta:
          dagster:
            asset_key: ["ynab_transactions"]
